---
- hosts: localhost
  tasks:
  - name: get the details of ec2
    ec2:
      ec2_url: 
      aws_access_key: 
      aws_secret_key:
      aws_region: us-east-2
      key_name: <awskey>
      instance_type: t2.micro
      image: ami-0520e698dd500b1d1
      
  - name: Take a snapshot of a EBS volume
    ec2_snapshot:
      volume_id: 
      description: snapshot of /data from DB is Taken /Date and Time
  - debug:
      msg: snapshot taken

