---
- hosts: localhost
  become: true
  vars_prompt:
    - name: "disk_name"
      prompt: "Raw disk used for create a Physical Volume"
      private: no
    - name: "part_size"
      prompt: "Size of the raw disk used for create a Physical Volume"
      private: no
    - name: "vg_name"
      prompt: "Name of the Volume Group"
      private: no
    - name: "lv_name"
      prompt: "Name of the logical Volume"
      private: no
    - name: "lvm_size"
      prompt: "Size of Logical volume to be created."
      private: no
    - name: "mount_location"
      prompt: "Mount the filesystem under."
      private: no
    - name: "file_sys_type"
      prompt: "Name of the File_System"
      private: no
  roles:
  - lvmtest

