---
- hosts: localhost
  become: true
  tasks:
  - name: check httpd at the latest versionm
    yum:
      name: httpd
      state: latest
  - name: install httpd
    yum:
      name: httpd
      state: installed
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: check httpd status
    command:
      cmd: service httpd status
  

